### ISSUE TITLE
Add "skip" setting to tilesets to skip processing it

### ISSUE THREAD

**Issue by agmcleod** [melonjs/melonJS#877]
Came up in forum here: http://www.html5gamedevs.com/topic/28667-feature-request-or-how-to-load-level-without-loading-all-tileset/. User wants the ability to skip processing a tmx tileset, where it used for more level design assistance instead of actual game information.

Such a setting could apply to regular layers as well.

**Comment by parasyte** [comment]
I would think this is more of a problem with use case than a real "feature". The TMX references a tileset, so it must be used somewhere (answer: it's used in the editor for layout etc). But unless that tileset reference is removed, and the layers which use that tileset are also removed, the game engine will still attempt to use these things (just like Tiled does).

IMHO, this should be fixed with a better workflow that can optimize the TMX during the build stage. I only know of a few tools that can do TMX optimizations, but this is really a much better idea than creating features just to suit one developer's weird use case.

* https://github.com/falanxia/tileset_baker
* https://github.com/danhp/tmxOptimizer

**Comment by harrisyu** [comment]
This is my solution : 
http://www.html5gamedevs.com/topic/28717-my-melonjs-learning-note-using-tile-to-defind-entity-in-tiled/
And it's easy, Thank you @agmcleod and @parasyte .

**Comment by obiot** [comment]
is my understanding correct ?
http://www.html5gamedevs.com/topic/28717-my-melonjs-learning-note-using-tile-to-defind-entity-in-tiled/
if yes we then then have a built-in mechansim :
https://github.com/melonjs/melonJS/blob/master/src/level/TMXTiledMap.js#L436-L453

As for optionally load a complete tileset, i'm a bit confused, as it just can then be removed directly from Tiled

**Comment by harrisyu** [comment]
I have post more detail in
http://www.html5gamedevs.com/topic/28717-my-melonjs-learning-note-using-tile-to-defind-entity-in-tiled/
And I still not understand the "built-in mechansim":
pull function will do:
throw new me.Error("Cannot instantiate entity of type '" + name + "'");
before:
                    // skip if the pull function does not return a corresponding object
                    if (typeof obj !== "object") {
                        continue;
                    }

**Comment by parasyte** [comment]
^ Good catch. The return type check predates the exception. So this is just dead code that we didn't actually know about.
